Updated to beta.16
FriendsOfFlarum/sitemap pull request #23
Opened 2021-03-24 19:02 UTC by skmedix

2021-03-25 15:36 UTC, askvortsov1 commented on js/package.json
> -        "webpack": "^4.26.0",
Are these changes necessary for this PR?

2021-03-25 15:37 UTC, askvortsov1 reviewed
I would recommend dropping all the FoF components stuff, and using the `buildSettingComponent` method on `ExtensionPage` where necessary.

2021-03-25 16:19 UTC, skmedix commented on js/package.json
> -        "webpack": "^4.26.0",
It's for consistency with other fof extensions

2021-03-25 16:20 UTC, skmedix commented
@askvortsov1 I dropped `fof/components`, I didn't amend this commit for better diff. Feel free to squash this PR on merge

2021-03-25 16:22 UTC, askvortsov1 approved these changes

2021-03-25 16:27 UTC, askvortsov1 requested changes
Actually, a few more changes needed to avoid deprecated stuff:

- The `app` helper is used in the migration. TBH, that migration should be updated to use the Flarum migration helper:
```
Migration::addSettings([
    'fof-sitemap.mode' => 'run',
    'fof-sitemap.frequency' => 'daily'
]);
```

In extend.php, an old closure-based extender is used to register service providers. These will be removed in stable; the service provider extender should be used instead.

2021-03-25 17:04 UTC, askvortsov1 approved these changes

2021-03-25 17:55 UTC, davwheat requested changes

2021-03-25 17:55 UTC, davwheat commented on js/src/admin/index.js
> +import app from 'flarum/common/app';
This isn't shared between forum and admin, so we should use `admin` here.

```suggestion
import app from 'flarum/admin/app';
```

2021-03-28 02:11 UTC, davwheat approved these changes
Not tested locally, but all looks good to me!

I trust Sasha's review :P

2021-03-28 02:14 UTC, merged